### ISSUE TITLE
Volt?

### ISSUE THREAD

**Issue by iambateman** [joserick/laravel-livewire-discover#1]
Cool package! Any idea if it can work with Volt?

### config

```php
'class_namespaces' => [
         'tools' => 'App\\Tools',
    ],
```

### App/Tools/test.blade.php 

```php
<?php

use Livewire\Volt\Component;

new class extends Component {


} ?>

<div>
    Hi!
</div>
```

### Home page
On the home page, I'm calling `<livewire:tools-test />` and getting `Unable to find component: [test]`

The package is definitely trying, because it would say [tools-test] if not. 

Any idea what I missed?

**Comment by joserick** [comment]
Hello

Volt already has its own discover, to add it you have to go to the VoltServiceProvider.php file, and add the new path:

```php
/**
 * Bootstrap services.
 */
public function boot(): void
{
    Volt::mount([
        config('livewire.view_path', resource_path('views/livewire')),
        resource_path('views/pages'),
        app_path('Tools'), // <-- Added new component path "App/Tools/"
    ]);
}
```
Just keep in mind that this one does not use prefixes so it would just be: `<livewire:test />`

**Comment by iambateman** [comment]
YOU ROCK!

Thank you so much for your help, that was exactly what I needed.

Very cool.
