### ISSUE TITLE
Livewire::discover and Livewire::discovers not working when previously set nonexisting namespace

### ISSUE THREAD

**Issue by misog** [joserick/laravel-livewire-discover#7]
Hi, I use Livewire::discover in a loop. When it is called with nonexisting namespace (empty folder with no php files) then it behaves like it just skips the discovery without any error.

The problem is, it also prevents future Livewire::discover discoveries in the loop.

This also applies for Livewire::discovers.

This happens in version 1.0.0 as well as in 1.1.0

**Comment by joserick** [comment]
Hi @misog 

I can't replicate the error:

`AppServiceProvider.php`
```php
    public function boot()
    {
        Livewire::discovers([
            'test' => 'App\\Test', // <-- No nonexisting namespace (empty folder with no php files)
            'dicover' => 'App\\Discover'
        ]);
    }
```

`welcome.blade.php`
```html
<livewire:discover.new-post /> // <--- Yes it works.
```

I don't know if I misunderstood.

**Comment by misog** [comment]
Hi, this does not work - it will not discover existing components out of ~5 folders:
```PHP
// foreach block ...
    Livewire::discover(
        $serviceName,
        "App\\Services\\{$serviceNameSlash}\\Components",
    );
// endforeach block ...
```
```
 Livewire\Exceptions\ComponentNotFoundException
Unable to find component: [AdminService.TestService.TestComponent]
```
(`$serviceName` equals `"AdminService.TestService"`)

But when I use this workaround to check if folder exists then it works - it discovers existing components:
```PHP
// foreach block ...
if (file_exists(app_path("Services/{$serviceNameSlash}/Components"))) {
    Livewire::discover(
        $serviceName,
        "App\\Services\\{$serviceNameSlash}\\Components",
    );
}
// endforeach block ...
```

The file check is the only change which makes the difference. The difference from your example is that in my case some folders are non-existing (not just empty). So the issue can be that it will stop working if folder path is non-existing when trying to load class from namespace.

**Comment by joserick** [comment]
Hi @misog 

This is the folder tree:

![Captura desde 2024-10-16 18-05-41](https://github.com/user-attachments/assets/60f21d52-a13f-4178-aa96-d1235e38890e)

Loop: 
```php
foreach ([
    'AdminService.TestService1' => 'Test1News', // <-- No exist folder Test1News
    'AdminService.TestService2' => 'Test2News', // <-- No exist sub-folder Components
    'AdminService.TestService3' => 'Test3News', // <-- No exist files .php
    'AdminService.TestService4' => 'Test4News', // <-- Yes exist folder, sub-folder and file "TestComponent.php"
] as $serviceName => $serviceNameSlash) {
    Livewire::discover(
        $serviceName,
        "App\\Services\\{$serviceNameSlash}\\Components",
    );
}
```

View:
```html
<livewire:AdminService.TestService4.TestComponent /> // <--- Yes it works.
```

Unsuccessful attempt to replicate bug.

`($serviceName equals "AdminService.TestService")` 
**aren't you using the same prefix ($serviceName="AdminService.TestService") for all foders???**
